### ISSUE TITLE
"Google Bookmarks will no longer be supported"

### ISSUE THREAD

**Issue by thedivclass** [ldenoue/yawas#12]
Hi there, big fan of yawas - just a quick query: 

As Google Bookmarks will "no longer be supported" after September 30th, 2021 [[source](https://www.androidpolice.com/2021/07/20/google-is-killing-bookmarks-no-not-your-browser-bookmarks/)] - are there any plans to migrate to an alternative bookmarking service? If so, might I suggest [pinboard](https://pinboard.in/api/) - which, despite being a paid service, has many blessings, including; descriptions of unlimited length, a privacy focus and a plethora of community creators and resources. 

Thank you for providing and maintaining this excellent utility

**Comment by thedivclass** [comment]
Sounds excellent - more the merrier! 

Suggested considerations: 
- pinboard
- [raindrop](https://raindrop.io/)
- google sheets
- (google bookmarks)

Alternative considerations - less/not suitable:
  - Notion
  - Evernote
  - Outliners: Workflowy, Dynalist, Roam Research
 

Thanks again

**Comment by ldenoue** [comment]
@thedivclass I just got an idea: why not use the built-in chrome.bookmark API?
https://developer.chrome.com/docs/extensions/reference/bookmarks/

It only has `title` and `url` fields but we could store the highlight inside the `title` like `TITLE#__#ANNOTATIONS`

And when users first start Yawas, they could be asked `Do you want to export your Google Bookmarks to Chrome Bookmarks?`

**Comment by thedivclass** [comment]
While any solution would be greatly appreciated, my only concern with using titles in this fashion is if the archive of bookmarks becomes illegible as a historical and searchable resource. I can appreciate this may be a nonissue for users who predominantly sought web highlighting functionality from yawas. Personally I don't fall into that camp, but given this discussion is about replacing google bookmarks, a product without any meaningful updates in a decade, it wouldn't surprise me if I was in the slim minority here. 

(An accessible and orderly bookmark log was one of the key determinants in suggesting pinboard initially - perhaps this can be considered or reassessed at some point in the future?)

If this is the chosen implementation, could Firefox bookmarks be included as a 'Google-free' alternative? (It too lacks the description field).

Once again, thank you!

**Comment by ldenoue** [comment]
Firefox implements the same API for bookmarks, and also has an options to sync them across several Firebox browsers. I'll do some testing about adding long text inside the title field to see the limit.

**Comment by ldenoue** [comment]
@thedivclass implemented saving to chrome.bookmarks and added a button on the popup that lets you import all your google bookmarks into chrome.bookmarks.
See the last 2 commits: https://github.com/ldenoue/yawas/commits/master

**Comment by thedivclass** [comment]
Hey @ldenoue, loving the update, it looks like the Firefox title field limit is 4096 characters - to extend the number of highlights that can be taken (and stored) on any given webpage, could an option to use truncated text excerpts be included, e.g. `<<Identifier~~End of excerpt>>`?
