### ISSUE TITLE
FYI: Incomplete data with API for www.google.com/bookmarks

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#13]
Hi Laurent,

Thank you on working on import from G. Bookmarks. What a hope for users of Yawas.

I'm going to create a few issues - all related to G. Bookmarks, but I'm separating them to minimize the noise here. This issue is only an FYI, and it may not even apply (since I don't know what G. Bookmarks API endpoint you use, or whether Google has fixed the below issue - which would be unlikely...).

https://www.google.com/bookmarks/lookup?output=rss doesn't include *some* labels (and their respective bookmarks - regardless of Yawas << ... >>). For my full report see https://support.google.com/chrome/thread/95429735/incomplete-data-with-api-for-www-google-com-bookmarks.

That started only once I reached a high number of G. Bookmarks. (I don't know how many of all G. Bookmarks I have, but my current export from G. Bookmarks - GoogleBookmarks.html - is 3.1MB big. Out of all of them 3620 contain Yawas highlights.) So it may not bother most users. Of course, feel free to close it if it doesn't apply (and even \if it applies, there's not much Yawas could do, other than going through all G. Bookmarks one by one).

**Comment by ldenoue** [comment]
@peter-kehl could you try going to https://www.google.com/bookmarks/bookmarks.html?hl=en
in the exported HTML, do you see all your bookmarks and fields you are expecting?
If so, we could use that instead of the output=rss or output=xml.

**Comment by peter-kehl** [comment]
Thank you Laurent. It seems that highlights get imported. Either Google fixed their API, or YAWAS import loop fixes it.
