### ISSUE TITLE
G. Bookmarks import to Firefox

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#15]
Hi Laurent,

In case you have a Firefox version that could import from G. Bookmarks, could you publish it, please? https://addons.mozilla.org/en-US/firefox/addon/yawas-web-and-pdf-highlighter and https://addons.mozilla.org/en-US/firefox/addon/yawas-web-and-pdf-highlighter/versions only show the old one.

Thank you for considering.

**Comment by ldenoue** [comment]
@peter-kehl I submitted it to Firefox today. Hopefully it'll get accepted soon.

**Comment by ldenoue** [comment]
It looks like it's published now https://addons.mozilla.org/en-US/firefox/addon/yawas-web-and-pdf-highlighter/
