### ISSUE TITLE
Firefox G. Bookmarks import: tags/labels

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#17]
I confirm that Yawas highlights in G. Bookmarks do get imported to Firefox (to the URL hash part), and they do get highlighted. (I haven't tried many of my Yawas-generated bookmarks yet, but if Google omits some of my bookmarks, that is a lower priority.)

Any chance to import G. Bookmarks' label(s) as Firefox bookmark 'tag(s)', please?

**Comment by peter-kehl** [comment]
Alternative/workaround recipe: Import G. Bookmarks labels as Firefox bookmarks sub-folder names.

That's the default migration when you use https://www.google.com/bookmarks/ > "Export bookmarks", you save it (as GoogleBookmarks.html) and you import it at Firefox menu > Bookmarks > Manage Bookmarks > menu "Import and Backup" > "Import bookmarks from HTML..." > choose that GoogleBookmarks.html file. That will create the bookmarks in folders reflecting G. Bookmarks labels.

However, to make Yawas import its highlights into/on top of the imported GoogleBookmarks.html, you need:

1. Before exporting to GoogleBookmarks.html, remove any extra labels. You want every G. Bookmark to have maximum one label. Otherwise Yawas will store the highlight in only one of the several (Firefox-imported) bookmarks, and it may be confusing.

2. While GoogleBookmarks.html is Firefox-compatible, it's not Yawas-compatible. (In short: ADD_DATE field in GoogleBookmarks.html has many more digits than ADD_DATE in HTML exported from Firefox Bookmarks. Most likely Firefox expects the timestamp in seconds, while GoogleBookmarks.html has it in microseconds or some other value.) Firefox does import GoogleBookmarks.html, but it ignores its ADD_DATE. The result imported bookmarks don't have "Added" field in Firefox. That's a problem for Yawas, which uses a Firefox API that requires the "Added" timestamp to exist. Working around that is probably out of scope, or even impossible for Yawas.)
To work around, if you don't need to preserve the timestamp, before you import GoogleBookmarks.html to Firefox, replace all occurrences of ADD_VALUE="..." (or regex ADD_DATE="[0-9]*") with a current timestamp, e.g. ADD_DATE="1627757727".

3. Import GoogleBookmarks.html to Firefox.

4. Run Yawas import (with option `chrome.bookmark API (unlimited)`).

**Comment by ldenoue** [comment]
@peter-kehl do you think that importing from GoogleBookmarks.html would be better than using RSS or XML?

`ADD_DATE` seems to correspond to the dates when a `LABEL` is added, not when the bookmark itself was added.
The unit seems to be microseconds, not even milliseconds, but it's trivial to convert to a correct date.

The thing is, I don't see any way to add a LABEL field to a Bookmark programmatically created with the chrome.bookmark API https://developer.chrome.com/docs/extensions/reference/bookmarks/

I only saw the `title` and `url` fields, which Yawas uses to import your `GoogleBookmarks.html`, thus leaving out labels and their dates.

Did I miss something?

**Comment by peter-kehl** [comment]
@ldenoue I'm happy with the current import.

The problem with GoogleBookmarks.html is that if a bookmark has multiple labels, GoogleBookmarks.html generated by Google Bookmarks "Export" has one distinct entry per each label per same bookmark. That's why above I suggested manual step number 1. when the user removes any extra labels (at least from bookmarks that have Yawas-stored highlights) and leaves one, or no, label per each Yawas bookmark in Google Bookmarks (before exporting). 

Otherwise Yawas import puts the highlights in only one of those matching bookmarks.

**Comment by peter-kehl** [comment]
All fine as-is. Thank you.
