### ISSUE TITLE
Update LICENCE on firefox addons page

### ISSUE THREAD

**Issue by parin23** [ldenoue/yawas#23]
As of now the firefox addons page shows the wrong licence. 
![image](https://user-images.githubusercontent.com/61468785/219938059-e86ab7d7-38c2-4c82-b868-d986155a657e.png)

It is misleading. Can hurt more people adopting it.
It's MIT Licence here vs All Rights reserved in the firefox addons store.

**Comment by parin23** [comment]
@ldenoue

**Comment by ldenoue** [comment]
I fixed it a few weeks ago. 
https://user-images.githubusercontent.com/149561/224480323-29dfd1d8-6405-4c6d-8f45-0697479527c8.mp4

**Comment by parin23** [comment]
Great work !! 
Thanks
