### ISSUE TITLE
Please use rgb(255, 255, 102) for yellow highlight

### ISSUE THREAD

**Issue by andromeda951** [ldenoue/yawas#24]
I fell rgb(255, 255, 102) to be softer than yellow color, the result nice to read, you can try it, please use this color.

check this for comparison
https://drive.google.com/drive/folders/1_CNC05Q9HdM64_SuJng6QrjHjlkrErhG?usp=sharing

**Comment by andromeda951** [comment]
[https://drive.google.com/file/d/1oJZobynY6TaIKDvO-TYw-_PrNt8jSNT1/view?usp=sharing](url)

**Comment by ldenoue** [comment]
Good idea, fixed.
