### ISSUE TITLE
Always "Signed out" in Firefox

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#3]
Hi Laurent,

YAWAS in Firefox is showing "Signed out", even though I'm logged on to G. Bookmarks. It started at least a week ago. Both in Firefox 69 and 70.0a1 (2019-08-23) x64 on Linux.

This may be a Firefox problem (I think it started with an upgrade to 69.0.2), or an interaction with another extension (though I haven't installed any new ones). I'll follow up with you.

![image](https://user-images.githubusercontent.com/4270240/66437330-546dbc00-e9de-11e9-9507-5d848c87ad59.png)

**Comment by ldenoue** [comment]
I believe it's fixed in this commit https://github.com/ldenoue/yawas/commit/464885cc845c2a3e36018713dea97e3746e9cd57

**Comment by peter-kehl** [comment]
Thank you :+1:
