### ISSUE TITLE
Option to store full highlighted text

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#4]
Hi Laurent,

It seems that for highlighted sections longer than around 18 characters, Yawas is storing them like <<numeric-length~~first-7-or-8-characters last-7-or-8-characters>>. Is that a workaround for Google's limit of 2K per bookmark note? If so, thank you, as many people will appreciate it.

On the other hand, some people may prefer to store all highlighted text - even though it means a limit for the highlights. Why? For example, they
- depend on the whole highlighted text to be in G. bookmarks, so they can search for it (on G. Bookmarks page),
- have a fear of missing out, and/or they use the highlights as a backup for pages that are known to change their content.

Could we have an option/checkbox to keep the whole text, please?

**Comment by ldenoue** [comment]
Hi Peter,

Yes it stores them in this compressed manner but only if the total amount is above the Google Bookmark limit. Otherwise it stores your highlights in fully.

Laurent

**Comment by peter-kehl** [comment]
Wow. You made it user-friendly.
That's why I haven't seen the Google API failure (the total limit) for a while...

How about indicating the number of characters left for highlighting (when storing in G. Bookmarks) at the bottom right, please?

**Comment by ldenoue** [comment]
I added a caption below to show the number of characters used so far out of 2048.
See commit https://github.com/ldenoue/yawas/commit/03353de407428036950d15aa5a9141a412aab313
and I submitted version 7.2.5 to Mozilla.

**Comment by peter-kehl** [comment]
Wow. Thank you.

Merry Christmas.
