### ISSUE TITLE
Deleting a highlight keeps it in G. Bookmarks

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#6]
Hi Laurent.
Deleting a highlight removes it from "XYZ/PQR highlishts" counter, and it removes the highlight color on the page. However, it keeps it in G. Bookmarks.
1. One new highlight:
![image](https://user-images.githubusercontent.com/4270240/71564524-8ed37c00-2a56-11ea-9e79-8ff851d183f1.png)
2. Deleted that highlight, added a different one (elsewhere). Checked https://www.google.com/bookmarks. Both are there (that means, the first one has not been deleted).
3. Added another highlight across a part of the text that was in the first (supposedly removed) highlight. Didn't refresh the page neither restarted Firefox. The page shows the 2nd and 3rd highlight only:
![image](https://user-images.githubusercontent.com/4270240/71564542-ed005f00-2a56-11ea-892b-c8a8ed7573b7.png)
4. However, G. Bookmarks show all three:
![image](https://user-images.githubusercontent.com/4270240/71564544-086b6a00-2a57-11ea-8ad3-d87446d51e59.png)
5. After refreshing the page, it now shows all three highlights:
![image](https://user-images.githubusercontent.com/4270240/71564547-2042ee00-2a57-11ea-8e3a-2278a52cc7b8.png)

**Comment by ldenoue** [comment]
Thanks for the detailed report and screenshots. I’ll look into this ASAP.

**Comment by ldenoue** [comment]
It's working well for me.
The highlights are deleted visually AND when I open the page to edit it https://www.google.com/bookmarks/

The "Notes" field is indeed empty.

To delete the highlight, I mouse over it and right click to select "Yawas Delete" from the context menu.

**Comment by peter-kehl** [comment]
Still the same problem with Firefox 72.0.1 or 72.0.2 and G. Bookmarks. No error in Browser Console.

**Comment by ldenoue** [comment]
Fixed in 7.2.6

**Comment by peter-kehl** [comment]
Thank you :+1:
