### ISSUE TITLE
Changing a color of an existing highlight fails in Firefox

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#7]
Hi Laurent,

With Firefox 72.0.1 or 72.0.2 and G. Bookmarks: When mouse-over an existing highlight. Then right-click or context menu key > Yawas > choose a color different to the existing highlight. The highlight color on the screen changes successfully.

However, the change is not pushed to G. Bookmarks. And in Firefox menu > Tools> Developer > Browser Toolbox > Console you get the below two errors.

Side note: Do not use Tools > Developer > Browser Console, because it shows only one of those two errors (or those two locations).

![image](https://user-images.githubusercontent.com/4270240/72940701-28bfd900-3d24-11ea-8764-064c6c11c5c9.png)

**Comment by ldenoue** [comment]
fixed in 7.2.6

**Comment by peter-kehl** [comment]
Thank you :+1:
