### ISSUE TITLE
"Receiving end does not exist"

### ISSUE THREAD

**Issue by peter-kehl** [ldenoue/yawas#8]
Highlighting any context at https://stuff.mit.edu/afs/sipb/project/android/docs/google/backup/
fails with:
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. yawas-background.js:246
sendMessageActiveTab moz-extension://778d06eb-f55c-4ded-a7b2-0206a5f0d806/yawas-background.js:246
```
Dev Tools > Browser Toolbox > Console:
![image](https://user-images.githubusercontent.com/4270240/73317565-640e4c00-41eb-11ea-8a10-bee7752ec15c.png)

Nothing comes to G. Bookmarks. At the same time (before and after this highlight), saving highlights on other webpages works fine. The error keeps happening even after restarting Firefox.

**Comment by ldenoue** [comment]
this page throws security errors in javascript.
I've tried to change the way the background page sends events to the content scripts, but not to avail, see commit https://github.com/ldenoue/yawas/commit/bd9f433615292ecffde46f0c61675998ce8b75a8

At least it doesn't throw an error, but still, the content script does not receive the event sent by the extension, so it doesn't highlight.
